name: ğŸš€ Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: flutter
          package-name: "project"
          changelog-types: |
            [
              {"type":"feat","section":"âœ¨ Features"},
              {"type":"fix","section":"ğŸ› Bug Fixes"},
              {"type":"perf","section":"âš¡ Performance"},
              {"type":"refactor","section":"ğŸ§¹ Refactoring"},
              {"type":"docs","section":"ğŸ“ Documentation"},
              {"type":"chore","section":"ğŸ”§ Maintenance"},
              {"type":"test","section":"âœ… Testing"}
            ]
